### ISSUE TITLE
Does it come preflashed?

### ISSUE THREAD

**Issue by ssuukk** [sideprojectslab/c64-blue#3]
Hi!

I've just received an assembled version of Blue 64. The passthrough seems to work ok, as I can type on C64 keyboard, but the device itself keeps sending ghost keypresses (probably every second, not exactly random, the letters seem to repeat). Do I have to flash it? Can I debug it somehow?

**Comment by sideprojectslab** [comment]
Hi, sorry for the late reply. Either the board is defective or (more likely) it is stuck in a boot loop. Normally the boards come already flashed but who knows, yours might have been corrupted somehow. There are a few steps you can take: first of all I would suggest to follow the instructions on the readme here on github and make sure to flash the latest version of the firmware. If that doesn't fix your issue we can go on with debugging. Would you be able to build the project yourself on Windows with some guidance? This would make the debugging process very easy, otherwise I will provide you with a debug-enabled version of the firmware which will log all diagnostics on a UART terminal through the USB port

**Comment by ssuukk** [comment]
Sure, I have a few ESP32 projects, so I guess I can manage with debuggin this one!

**Comment by sideprojectslab** [comment]
allright perfect, would you like to join the discord server linked in the project readme? then we can troubleshoot more easily :)

**Comment by ssuukk** [comment]
sure, which one? :D

**Comment by sideprojectslab** [comment]
This one: https://discord.com/invite/gJsCgebkDw I am not aware of any others :D

**Comment by ssuukk** [comment]
Oh, there's thousands of them! Check out this cool one about Meatloaf - a C64 cloud drive on ESP!
